### ISSUE TITLE
navigator ua checks

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [hardenFF/tzp#57]
snip

**Comment by Thorin-Oakenpants** [comment]
CB 5.14 (because I was testing window.open)
![workers](https://user-images.githubusercontent.com/16656956/77938634-91d44780-72a5-11ea-92b4-b9c839f60568.png)

`let list = ['userAgent','appCodeName','appName','product','appVersion','platform']`

Looks like item 4, appVersion` is/was fubared
- worker says 5.0 (Windows) = correct for Firefox
- document says `blahblah massive string` which is correct for Chrome

Most of he others don't differ because only a few nav properties are available in workers, and they happen to be the same: I mean everyone is
```
appCodeName	Mozilla
appName	Netscape
product	Gecko
platform	Win32 <-- for windows
```

not sure why userAgent seems to be covered by appVersion isn't

I'll test CB stable release and post back

**Comment by Thorin-Oakenpants** [comment]
OK, CB 1.2, I turned on nav protection and fakes at MacOSX, Safari (am on windows 7)

no match
```
WORKER
00 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14.3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
01 Mozilla
02 Netscape
03 Gecko
04 5.0 (Windows)
05 Win32 worker_ua.js:11:10

DOCUMENT
00 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14.3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
01 Mozilla
02 Netscape
03 Gecko
04 5.0 (Macintosh; Intel Mac OS X 10.14.3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
05 MacIntel
```

looks like 'appVersion' and 'platform' leak

**Comment by Thorin-Oakenpants** [comment]
OK - I found an extension that doesn't properly spoof navigator in iframes [agentium](https://addons.mozilla.org/en-US/firefox/addon/agentium/) - I installed the older version in Nightly and used browserleaks [js page](https://browserleaks.com/javascript) to check it.

I updated TZP iframe nav check to run code from the parent, but it doesn't pick up a non-match, so I'm clearly doing something wrong

**Comment by Thorin-Oakenpants** [comment]
`CB v1.2` updates

only 6 nav properties are available: I spoofed them as 00 to 05 (using my hash order), as per pic below
![spoof](https://user-images.githubusercontent.com/16656956/77984830-3ab09000-7302-11ea-9393-93373b0f3d9b.png)

https://thorin-oakenpants.github.io/testing/ - from console debug
```js
DOCUMENT
00 spoof00-userAgent
01 spoof01-appCodeName
02 spoof02-appName
03 spoof04-product
04 spoof05-appVersion
05 spoof03-platform

SHAREDWORKER
00 Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
01 Mozilla
02 Netscape
03 Gecko
04 5.0 (Windows)
05 Win32

WORKER
00 spoof00-userAgent
01 Mozilla
02 Netscape
03 Gecko
04 5.0 (Windows)
05 Win32
```

As you can see there are a 5/6 leaks in worker, and 6/6 leaks in shared worker. Am about to add service worker

**Comment by kkapsner** [comment]
> kkap ... where are ya?
I was in bed... I think we are in different time zones.

In my navigator test for CB I do not load any resource. I simply use the window object already present when only creating a frame. With `window[0]` you can directly access the first frame and use the properties there.
When you are loading a resource it's easier for webExtensions to spoof there. So I would not use a resource there.

Regarding the service workers: the userAgent used to always match the value in the HTTP request which can easily be changed. It seems that the worker still does that. But for the others a webExtension has no way to spoof something there (as far as I know). So that will leak the navigator values

**Comment by Thorin-Oakenpants** [comment]
Cool. I wonder if I can trap an error there if for example, uMatrix blocked iframes

I'm still not sure how to do this?
```
try
   create iframe
   connect to iframe window[0]
     blah blah
     now do a nested iframe
     run cleanup(remove iframes)
catch
   iframe is blocked
   run cleanup( remove iframe)
```

I'll give it a shot, but I'll probably need some help

---

workers etc: that sucks

**Comment by Thorin-Oakenpants** [comment]
> workers etc: that sucks

can't wait for the day people realize spoofing the UA is a waste of time
 - except maybe for compat

![lies](https://user-images.githubusercontent.com/16656956/78098425-9b0d0380-73ce-11ea-90fb-fba799d92bb6.png)

**Comment by kkapsner** [comment]
I think I should include the workers in my CB test page...

**Comment by Thorin-Oakenpants** [comment]
**let me know** when you code the bit that lets you listen for (and act on) a registration.active for service workers --> https://github.com/Thorin-Oakenpants/testing/blob/master/js/testing.js#L78 

At the moment I'm just parsing shared worker to output the lies (but I still want to do service worker and nested worker: and I'll combine common hashes). If workers are available, then a shared worker seems to cover the max possible lies

What I then need to do is all that iframe stuff: same thing: combine common hashes, and detect lies <-- need some help on all that promise async callback wizardry

Red dots: -> I also have my own feature detection of lies which also picks up on implausible values like typos, extra spaces, etc - still working on it: it's based on Firefox's own code and super sexy and intelligent if I might say so

And then I'll combine all three sources of lies (iframes, workers, feature detection & implausible) into some sort of lies handling function

It's all terribly exciting :)

**Comment by Thorin-Oakenpants** [comment]
What you can't see there are the double spaces, leading space, trailing space (I should make those show on the output). And it is based on on the OS detected in the widget test. I'm yet to code the bit for the full userAgent string, since that has at least three different ways to fail, one of which has some exceptions (for RFP)

I'm going to change the arrow to red dots, and the line to just a red dot, with the word : lies

or maybe `utter bullshit detected` 👍 

![more-lies](https://user-images.githubusercontent.com/16656956/78146566-d84eb100-7421-11ea-83e6-83a3bc2249b8.png)

**Comment by Thorin-Oakenpants** [comment]
A: yay! finally worked out how to detect from the client when a service worker changes state - and I then send the sw a message, and it replies on a broadcast channel.

B: But I don't need it. I just make sure to unregister the sw at the end, and use the activate event in the sw itself

Both tests (A and B) on page load (B is what is currently live), do a single broadcast. But when you re-run they do multiple (2 or 3). You can see it in the console at https://thorin-oakenpants.github.io/testing/

page load : the number is just `performance.now()`
```
shared 741
service 770
web 882
```

rerun
```
shared 78974
web 79001
service 79266
service 79268 <-- is only 2 ms, but why do service twice?
```

next rerun = 3 x service, then next rerun = 4, and then 4 again

Not sure if that can be eliminated or is important?

**Comment by kkapsner** [comment]
>     * is `window[window.length - 1]` the one that causes a popup request? cuz I don't really want a popup (but interesting how this triggers a warning bar that has height entropy based on language)

This is a method to access the latest added iframe. The popup is from window.open.


> **let me know** when you code the bit that lets you listen for (and act on) a registration.active for service workers --> https://github.com/Thorin-Oakenpants/testing/blob/master/js/testing.js#L78

https://github.com/kkapsner/CanvasBlocker/blob/master/test/navigatorTest.js and https://github.com/kkapsner/CanvasBlocker/blob/master/test/navigatorTestWorker.js

> need some help on all that promise async callback wizardry

It's not that complicated once you understand that async and await is only syntactic sugar and how Promises work.

**Comment by Thorin-Oakenpants** [comment]
> when you code the bit that lets you listen for 

Yeah. I worked all that out a almost two weeks ago. But it's all not quite the same as yours. I use a broadcast

I think I need a **lot** of help here
- to add a nested worker, and that worker from blob
   - along with worker, shared worker, service worker = that makes five checks
- to combine my current three worker js files into one like yours
- all five checks push all six results into a global array
- know when all five finish - so that would be promises, right?
   - this is the trigger for me to turn those 5 checks x 6 results = array of 30 items => unique results which I then output if they differ to the control value, and also my trigger to compare the five hashes and combine results if the hash is the same (cosmetic: reducing lines)

I also need to be able to detect failures: e.g when cookies are blocked, sw's are disabled, or if uMatrix blocks workers: this is crucial so that I always output a result, and so the five "promises" resolve -> leads to the output/compare trigger

Am I making sense? In my code I have this
```js
		if ("serviceWorker" in navigator) {
			// assume failure
			el5.innerHTML = zF + " [A: assumed]"
			// register
			navigator.serviceWorker.register("js/workerservice_ua.js").then(function(swr) {

				// debug
				let sw
				if (swr.installing) {sw = swr.installing}
				else if (swr.waiting) {sw = swr.waiting}
				else if (swr.active) {sw = swr.active}
				sw.addEventListener("statechange", function(e) {
					console.debug("sw: " + e.target.state)
					if (e.target.state == "activated") {
						sw.postMessage("hi")
					}
				})

				if (sw) {
					// listen
					let channel = new BroadcastChannel("sw-ua")
					console.debug("listening for sw")
					channel.addEventListener("message", event => {
						test5 = sha1((event.data.msg).join())
						el5.innerHTML = test5 + (test5 == control ? match_green : match_red)
						// unregister
						swr.unregister().then(function(boolean) {})
						// close
						channel.close()
					})
				} else {
					el5.innerHTML = zF + " [B: not swr.installing]"
				}
			},
			function(e) {
				el5.innerHTML = zF + " [C: not registering]: "  + e.message
			})
		} else {
			el5.innerHTML = zF + " [D: no sw]"
		}
```

- note the four "failure" points: A, B, C, D. That's just for debugging: at the end of the day I will just return `n/a` if it's blocked or whatever. Sometimes, I get `A` as the final result, even though everything else fires: all the console messages, including from the service worker js: but the broadcast is not heard: I can replicate it if I open FF and then TZP as fast as possible (or sometimes on a restart after nightly updates and I have TZP open) - except now I can't replicate

^^ just saying that's it's really important that all errors are caught and something is always output

... and then after that, I'll need help with all that iframe stuff. I still can't make it refer to the window - and again .. promises .. so I can combine them all etc

**Comment by Thorin-Oakenpants** [comment]
> It's not that complicated once you understand that async and await is only syntactic sugar and how Promises work

I've tried. I spend days, weeks on it last year. Reading tutorials, etc, testing. I just cannot wrap my head around promises and I just end up with things that don't work or the syntax gets out of whack (frequently) and I have to start all over

**Comment by Thorin-Oakenpants** [comment]
Here we go: managed to repro again: just did a nightly update: had TZP open, clicked restart to apply changes

![eek](https://user-images.githubusercontent.com/16656956/79415021-bc0f5000-7f9b-11ea-9f65-acb4c86e63b1.png)

Looks like in some instances I'm starting to listen **after** the sw sends the message

**Comment by Thorin-Oakenpants** [comment]
and here's beta where I reproduced it
![eeeeeeek](https://user-images.githubusercontent.com/16656956/79437031-28e91100-7fc1-11ea-95b6-efdc3e6c988d.png)

client sends the message but the sw never gets it, despite being activated

**Comment by kkapsner** [comment]
Sorry for not responding so long. Is there still a problem or does it work now?

**Comment by Thorin-Oakenpants** [comment]
Still have the occassional error. I think I need to rework it. Today's nightly makes it fail a lot too. Actually error trapped with long error messages about failures. Even just doing a re-run. It's hit and miss a bit. I think the way I'm doing it is all a bit wrong.

I think once you help me (no hurry: I've been at this for 18 months, so I'll just keep plodding away) to turn the five of them (from blob and nested) into a single promise and a single worker js file (like yours), along with the iframe tests, the problem will probably go away. I don't know when I'll be able to face this: workers are bad enough, let alone nested, let alone combining them in a single file (I get onconnect errors) .. and then the promise do me in.
- it's like the movie inception: I need promises within a promise

```
promise (

     promise (
        get all five workers arrays/failures
     ) => output/display + combine/split worker hash lines

     promise (
        get all three iframe arrays/failures
     ) => output/display + combine/split iframe hash lines

) => combine all eight arrays and output unique leaks

```

The promise being that all five workers tests and all three iframe tests either fail or return an array. When I have eight results, and I need to know which array belongs to who, then I can
- combine them all into another new array and get unique leaks and output those leaks
- compare each one to the control (main page) and decide if it matches or not
- combine the hash/match results for less lines: e.g. if all iframe hashes are the same, then it's one line for iframes, same for workers

**Comment by kkapsner** [comment]
>     * I need promises within a promise

That's doable but a better way would be to have eight promises - one for each test. Then you can combine them with `Promise.all` in all the configurations you need them. Something like this (please use better names!):
```
var p1 = getWorker1Promise();
...
var p5 = getWorker5Promise();
var p6 = getIframe1Promise();
...
var p8 = getIframe3Promise();

Promise.all([p1, ..., p5]).then(outputWorkerData);
Promise.all([p6, p7, p8]).then(outputIframeData);
Promise.all([p1, ...., p8]).then(combineAndCompareAll);
```
`output...Data` and `combine...` get all called with one argument. This is an array of the results of the promises. E.g. `outputIframeData` gets this array as argument: `[resultFromIframe1, resultFromIframe2, resultFromIframe3]`.

The "failure" has to be coded so that it also resolves the promise - just with your error indication. Usually when something in the Promise code fails it rejects the promise.

**Comment by Thorin-Oakenpants** [comment]
Yeah, that's what I'm talking about. The eight arrays get created on the fly with autonames. And if there's an error, just push one result to the array: an error code or something. So I don't even need to check if service workers or workers etc are enabled (pref) or blockers (uMatrix) etc.
