### ISSUE TITLE
domrect /svg method tests are lacking

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [hardenFF/tzp#67]
So... where are all the tests for randomizing [all](https://thorin-oakenpants.github.io/testing/domrect.html) the methods in CB?

So I there are several things I want to achieve here
- 1 test that the method isn't blocked, and sure, things like SVG can be blocked by a pref rather than CB: that's ok, the error trapping can have some logic to it
- 2 get a value for that method
     - does it create entropy?
     - can it be used to validate other measurements
- 3 for CB users, a reloaded page should randomize those methods
- 4 can I detect if it's random
- 5 other: e.g. getExtentOfChar - can this be used for any precision and added to the unicode glyphs + textMetrics section?

@kkapsner and class, discuss!

**Comment by kkapsner** [comment]
> So... where are all the tests for randomizing [all](https://thorin-oakenpants.github.io/testing/domrect.html) the methods in CB?

Simple answer: nowhere
Long answer: just searched for DOMRect in the MDN documentation and applied my logic to them. Now that I have looked into it I see that Firefox does not follow their own documentation and I have to create the test for CB and fix the bug/quirks I find with it.

**Comment by Thorin-Oakenpants** [comment]
So for each
- create an element that has entropy and high precision (e.g. use text since fonts can differ, rotate things)
- add the element to the domrect overlay/iframe
- bonus if it can replicate a previous value? Not sure if this is really needed: it's good to confirm that the measurement is consistently randomized for stealth, and good to show that a different methods can still get the same value: But I do like new values as it probably adds better entropy

Links
- getBounds
- [MDN getBBox](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox)
- [MDN getExtentOfChar](https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement)
    - note: I do want to do a proper SVG section, maybe as a subsection under `DOMRect / SVG`
- [MDN intersectionRect](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/intersectionRect)
- boundingClientRect
- [MDN rootBounds](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/rootBounds)

**Comment by Thorin-Oakenpants** [comment]
Note that [source](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40060)
> As of Firefox 76, the `IntersectionObserver()` constructor now accepts a Document object as its root, as well as an Element object. This lets you explicitly use a window's entire content area as the intersection bounds. We should verify that this does not allow someone to defeat the protections provided by letterboxing (probably it does not)
