### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [hardenFF/tzp#72]
@kkapsner @abrahamjuliot 

reminder/question: can wasm be used to get properties and info? similar to how we use iframes or workers: e.g. navigator or screen values etc

**Comment by abrahamjuliot** [comment]
There are ways to use WASM to interact with browser APIs, but does WASM make way to create a virtual context or scope?  Iframes have their own browsing context/document environment, and Workers have their own global scope/event loop.

Here's an example of canvas fingerprinting in Rust.
- https://drbh.github.io/wasm-fingerprint/
- https://github.com/drbh/wasm-fingerprint/blob/master/src/lib.rs

**Comment by Thorin-Oakenpants** [comment]
> https://drbh.github.io/wasm-fingerprint/

Uncaught TypeError: wf.make_fingerprint is not a function
wasm-fingerprint:442:63

**Comment by kkapsner** [comment]
The timings in the script are too tight for Firefox. If you set a debugger break point at line 441 it works. AND CB is protecting against it!

**Comment by Thorin-Oakenpants** [comment]
I assume RFP also protects ?

**Comment by kkapsner** [comment]
Seems so.
