### ISSUE TITLE
timezones

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [hardenFF/tzp#75]
reminder: instead of hard coded dates, use set dates but current year: this allows for changes to DST in future

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot FYI: were you having issues with Date.parse ? [1655947](https://bugzilla.mozilla.org/show_bug.cgi?id=1655947)

**Comment by Thorin-Oakenpants** [comment]
since I'm checking for RFP ... I think I'll use this
```js
let yrs = ['2','555','995','1066','1815', ...
```

Seems UTC always returns `0` for everything
 - year `1` returns `NaN`s
 - in my real TZ (not UTC), single and double digit years like `2` or `10` return "normal" reults: i.e not `-353.33333` etc gibberish - so I guess they're treated as shorthand for e.g. 1902 or 2002

```
2:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
555:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
995:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1066:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1815:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1905:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1915:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1925:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1935:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1945:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1955:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1965:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1975:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1985:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
1995:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
2005:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
2015:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
2020:0, 0, 0, 0 | 0, 0, 0, 0 | 0, 0, 0, 0
```

I might change my system timezone around and see what other TZs produce. I got a feeling none will treat [1066](https://en.wikipedia.org/wiki/Battle_of_hastings) with non-gibberish.

Will be interesting to see how chameleon handles these whacky dates

**Comment by abrahamjuliot** [comment]
> issues with Date.parse?

No issues to my knowledge. But, I realized many regions have a history of switching timezones, and this history is accurately exposed in the Date object through the host system settings. It appears, when the date is roughly > 50 years old since the last change in the timezone (if any), the 1970 UTC calculated timezone offset will return floats.
